

on:
  workflow_dispatch:
    inputs:
      link:
        description: "Captcha Link"
        required: true
        default: "https://app.blasteronline.com/assets/captcha/1670931972.376.jpg"
name: Get Captcha
jobs:
  get:
    name: Get captcha
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: ['3.8']
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-python@v2
      - run: sudo apt update
      - run: echo $link; 
        env:
          link: ${{ github.event.inputs.link }}
      - run: pip install requests
        env:
          link: ${{ github.event.inputs.link }}
      
